### PR TITLE
Fapi fixes

### LINKED ISSUE #1606: FAPI: Exported Key lacks policy field
The FAPI exported keys lack the field policy.
See Fapi_Export and Fapi_Import

### PR DESCRIPTION
**Pull request by AndreasFuchsSIT**
This PR contains several fixes. Most notable:
- Fixes #1606 
- Add / Update doxygen headers and inline comments to many functions
- Some Null-Pointer and use-after-free fixes

This is part of our effort to stabilize towards release.
Sorry for the large pack of changes this late.

### CODE REVIEW

File: src/tss2-fapi/fapi_util.c [hunk 1]
```diff
@@ -450,6 +519,23 @@ ifapi_load_primary_async(FAPI_CONTEXT *context, char *path)
...
 
+/** State machine to finalize the loading of a primary key from key store.
+ *
+ * The asynchronous loading or the key from keystore will be finalized.
+ * Afterwards the hierarchy object, which will be used for authorization will
+ * be loaded and the ESAPI functions for primary generation will be called
+ * if the primary is not persistent.
+ *
+ * @param[in] context The FAPI_CONTEXT.
+ * @param[in] path The FAPI path of the primary key.
```
Comment (tstruk) [inline src/tss2-fapi/fapi_util.c]: That supposed to be the handle

File: src/tss2-fapi/fapi_util.c [hunk 2]
```diff
@@ -608,6 +725,14 @@ ifapi_non_tpm_mode_init(FAPI_CONTEXT *context)
     return TSS2_RC_SUCCESS;
 }
 
+/** Cleanup FAPI sessions in error cases.
+ *
+ * The uses sessions and the SRK (if not persistent) will be flushed
+ * non asynchronous in error cases.
+ *
```
Comment (tstruk) [inline src/tss2-fapi/fapi_util.c]: Add:
 @param[in] context The FAPI_CONTEXT.

File: src/tss2-fapi/fapi_util.c [hunk 3]
```diff
@@ -895,6 +1080,8 @@ ifapi_merge_profile_into_template(
     return TSS2_RC_SUCCESS;
 }
 
+/** Convert absolute path to FAPI path which can be used as parameter for FAPI commands.
+ */
```
Comment (tstruk) [inline src/tss2-fapi/fapi_util.c]: Add doxygen description for the params

File: src/tss2-fapi/ifapi_helpers.c [hunk 4]
```diff
@@ -2149,7 +2442,7 @@ write_curl_buffer_cb(void *contents, size_t size, size_t nmemb, void *userp)
  * @param[out] buffer_size The size of the retrieved object.
  *
  * @retval TSS2_RC_SUCCESS on success
- * @retval TSS2_FAPI_RC_BAD_REFERENCE if
+* @retval TSS2_FAPI_RC_BAD_REFERENCE if
```
Comment (tstruk) [inline src/tss2-fapi/ifapi_helpers.c]: ... if we would return it, but it looks like we don't.

File: src/tss2-fapi/api/Fapi_NvExtend.c [hunk 5]
```diff
@@ -119,6 +119,7 @@ Fapi_NvExtend(
  * @retval TSS2_RC_SUCCESS: if the function call was a success.
  * @retval TSS2_FAPI_RC_BAD_REFERENCE: if context, nvPath, or data is NULL.
  * @retval TSS2_FAPI_RC_BAD_CONTEXT: if context corruption is detected.
+ * @retval TSS2_FAPI_RC_BAD_VALUE: if dataSize is larger than 1024
```
Comment (tstruk) [inline src/tss2-fapi/api/Fapi_NvExtend.c]: The commit message disagrees the comment and the implementation.
