### PR TITLE
esys_iutil.c: Fix issue where nonceTPM was included twice in hmac

### LINKED ISSUE #2037: src/tss2-esys/esys_iutil.c: iesus_gen_auths adding encryptNonce and decryptNonce for non-encrypted sessions at index 0
@JuergenReppSIT, What is the reason for [this](https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-esys/esys_iutil.c#L1341:L1344) check?

Due to this, the authorization hmac session at index 0 is inadvertently including the encryptNonce and decryptNonce despite sessionAttributes indicating that the parameter encryption is turned off.

Issue also captured in [tpm2-tools](https://github.com/tpm2-software/tpm2-tools/issues/2377).

### PR DESCRIPTION
**Pull request by idesai**
Fixes #2037

TPM2.0 Architecture 19.6.5 Note 7

If the same session (not the first session) is used for decrypt and
encrypt, its nonceTPM is only used once. If different sessions are
used for decrypt and encrypt, both nonceTPMs are included.

Signed-off-by: Imran Desai <imran.desai@intel.com>

### CODE REVIEW

File: src/tss2-esys/esys_iutil.c [hunk 1]
```diff
@@ -1295,6 +1295,18 @@ iesys_gen_auths(ESYS_CONTEXT * esys_context,
...
     return_if_error(r, "More than one crypt session");
 
+    /*
+     * TPM2.0 Architecture 19.6.5 Note 7
+     *
+     * If the same session (not the first session) is used for decrypt and
+     * encrypt, its nonceTPM is only used once. If different sessions are used
+     * for decrypt and encrypt, both nonceTPMs are included
+     */
+    if (decryptNonceIdx == encryptNonceIdx) {
```
Comment (tstruk) [inline src/tss2-esys/esys_iutil.c:1305]: So it should perhaps be:
```
if (decryptNonceIdx > 0 && decryptNonceIdx == encryptNonceIdx) {
        decryptNonceIdx = 0;
}
```

Comment (JuergenReppSIT) [reply src/tss2-esys/esys_iutil.c:1305]: Yes I agree, to this solution. The encryptNonce should not be set to 0.

Comment (JuergenReppSIT) [reply src/tss2-esys/esys_iutil.c]: I would suggest:
```
if (encryptNonceIdx > 0 && decryptNonceIdx == encryptNonceIdx) {
        encryptNonceIdx = 0;
}

**Review by tstruk — APPROVED** [review]
Thanks for the fix @idesai
I will also cherry pick it to 3.0.x and 2.4.x

**Comment by idesai** [comment]
@tstruk can you please include this in 3.0.x and the latest 3.0.4-rc1?
