### PR TITLE
Fix indentation problems

### LINKED ISSUE #1053: Wrong indentation
According to the [coding standard](https://github.com/tpm2-software/tpm2-tss/blob/master/doc/coding_standard_c.md#whitespace), all indentation must be multiples of 4 spaces (and not tabs).

However, I found quite some tabs, e.g. in

- [src/tss2-esys/esys_iutil.c:203](https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-esys/esys_iutil.c#L203)
- [test/integration/sapi-hierarchy-change-auth.int.c:44](https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/sapi-hierarchy-change-auth.int.c#L44)
- ...

Also, there are indents which are not multiples of 4 spaces, e.g. in

- [test/integration/esys-nv-ram-extend-index.int.c:110](https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-nv-ram-extend-index.int.c#L110)
- [test/integration/esys-create-session-auth.int.c:179](https://github.com/tpm2-software/tpm2-tss/blob/master/test/integration/esys-create-session-auth.int.c#L179)
- ...

### PR DESCRIPTION
**Pull request by joholl**
According to the [coding standard](https://github.com/tpm2-software/tpm2-tss/blob/master/doc/coding_standard_c.md#whitespace), all indentation must be multiples of 4 spaces (and not tabs). Fixes #1053

### CODE REVIEW

File: src/tss2-esys/esys_iutil.c [hunk 1]
```diff
@@ -200,8 +200,8 @@ iesys_compute_encrypt_nonce(ESYS_CONTEXT * esys_context,
             if (session->rsrc.misc.rsrc_session.
                 sessionAttributes & TPMA_SESSION_ENCRYPT) {
                 if (*encryptNonce != NULL) {
-		    /* Encrypt nonce already found */
-		    return_error(TSS2_ESYS_RC_MULTIPLE_ENCRYPT_SESSIONS,
+            /* Encrypt nonce already found */
+            return_error(TSS2_ESYS_RC_MULTIPLE_ENCRYPT_SESSIONS,
```
Comment (AndreasFuchsSIT) [inline src/tss2-esys/esys_iutil.c]: These new indentations do not align
