### PR TITLE
ESYS: Updated to mbedTLS 3.0

### LINKED ISSUE #2266: Support mbedTLS 3.x
Hi.
Just to let you know, build fails when using mbedTLS 3.1.0:
```
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:534:44: error: too many arguments to function call, expected single argument 'ctx', have 3 arguments
            mbedtls_rsa_init(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA1);
            ~~~~~~~~~~~~~~~~               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/hpkg/4813f23393a8b1bccdceb77610e4b39c2f35c389-libmbedtls/include/mbedtls/rsa.h:59:33: note: expanded from macro 'MBEDTLS_RSA_PKCS_V21'
#define MBEDTLS_RSA_PKCS_V21    1 /**< Use PKCS#1 v2.1 encoding. */
                                ^
/hpkg/4813f23393a8b1bccdceb77610e4b39c2f35c389-libmbedtls/include/mbedtls/rsa.h:137:6: note: 'mbedtls_rsa_init' declared here
void mbedtls_rsa_init( mbedtls_rsa_context *ctx );
     ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:537:44: error: too many arguments to function call, expected single argument 'ctx', have 3 arguments
            mbedtls_rsa_init(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA256);
            ~~~~~~~~~~~~~~~~               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/hpkg/4813f23393a8b1bccdceb77610e4b39c2f35c389-libmbedtls/include/mbedtls/rsa.h:59:33: note: expanded from macro 'MBEDTLS_RSA_PKCS_V21'
#define MBEDTLS_RSA_PKCS_V21    1 /**< Use PKCS#1 v2.1 encoding. */
                                ^
/hpkg/4813f23393a8b1bccdceb77610e4b39c2f35c389-libmbedtls/include/mbedtls/rsa.h:137:6: note: 'mbedtls_rsa_init' declared here
void mbedtls_rsa_init( mbedtls_rsa_context *ctx );
     ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:540:44: error: too many arguments to function call, expected single argument 'ctx', have 3 arguments
            mbedtls_rsa_init(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA384);
            ~~~~~~~~~~~~~~~~               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/hpkg/4813f23393a8b1bccdceb77610e4b39c2f35c389-libmbedtls/include/mbedtls/rsa.h:59:33: note: expanded from macro 'MBEDTLS_RSA_PKCS_V21'
#define MBEDTLS_RSA_PKCS_V21    1 /**< Use PKCS#1 v2.1 encoding. */
                                ^
/hpkg/4813f23393a8b1bccdceb77610e4b39c2f35c389-libmbedtls/include/mbedtls/rsa.h:137:6: note: 'mbedtls_rsa_init' declared here
void mbedtls_rsa_init( mbedtls_rsa_context *ctx );
     ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:543:44: error: too many arguments to function call, expected single argument 'ctx', have 3 arguments
            mbedtls_rsa_init(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA512);
            ~~~~~~~~~~~~~~~~               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/hpkg/4813f23393a8b1bccdceb77610e4b39c2f35c389-libmbedtls/include/mbedtls/rsa.h:59:33: note: expanded from macro 'MBEDTLS_RSA_PKCS_V21'
#define MBEDTLS_RSA_PKCS_V21    1 /**< Use PKCS#1 v2.1 encoding. */
                                ^
/hpkg/4813f23393a8b1bccdceb77610e4b39c2f35c389-libmbedtls/include/mbedtls/rsa.h:137:6: note: 'mbedtls_rsa_init' declared here
void mbedtls_rsa_init( mbedtls_rsa_context *ctx );
     ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:594:43: error: use of undeclared identifier 'MBEDTLS_RSA_PUBLIC'
                                          MBEDTLS_RSA_PUBLIC,
                                          ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:606:48: error: use of undeclared identifier 'MBEDTLS_RSA_PUBLIC'
                                               MBEDTLS_RSA_PUBLIC,
                                               ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:664:49: error: no member named 'grp' in 'struct mbedtls_ecdh_context'
        if(mbedtls_ecp_group_load(&ecdh_context.grp, MBEDTLS_ECP_DP_SECP192R1) != 0) {
                                   ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:670:49: error: no member named 'grp' in 'struct mbedtls_ecdh_context'
        if(mbedtls_ecp_group_load(&ecdh_context.grp, MBEDTLS_ECP_DP_SECP224R1) != 0) {
                                   ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:676:49: error: no member named 'grp' in 'struct mbedtls_ecdh_context'
        if(mbedtls_ecp_group_load(&ecdh_context.grp, MBEDTLS_ECP_DP_SECP256R1) != 0) {
                                   ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:682:49: error: no member named 'grp' in 'struct mbedtls_ecdh_context'
        if(mbedtls_ecp_group_load(&ecdh_context.grp, MBEDTLS_ECP_DP_SECP384R1) != 0) {
                                   ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:688:49: error: no member named 'grp' in 'struct mbedtls_ecdh_context'
        if(mbedtls_ecp_group_load(&ecdh_context.grp, MBEDTLS_ECP_DP_SECP521R1) != 0) {
                                   ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:699:47: error: no member named 'grp' in 'struct mbedtls_ecdh_context'
    if (mbedtls_ecdh_gen_public(&ecdh_context.grp,
                                 ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:700:47: error: no member named 'd' in 'struct mbedtls_ecdh_context'
                                &ecdh_context.d,
                                 ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:701:47: error: no member named 'Q' in 'struct mbedtls_ecdh_context'
                                &ecdh_context.Q,
                                 ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:717:48: error: no member named 'Q' in 'struct mbedtls_ecdh_context'
    Q->x.size = mbedtls_mpi_size(&ecdh_context.Q.X);
                                  ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:722:48: error: no member named 'Q' in 'struct mbedtls_ecdh_context'
    if (mbedtls_mpi_write_binary(&ecdh_context.Q.X,
                                  ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:729:48: error: no member named 'Q' in 'struct mbedtls_ecdh_context'
    Q->y.size = mbedtls_mpi_size(&ecdh_context.Q.Y);
                                  ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:734:48: error: no member named 'Q' in 'struct mbedtls_ecdh_context'
    if (mbedtls_mpi_write_binary(&ecdh_context.Q.Y,
                                  ~~~~~~~~~~~~ ^
../tpm2-tss-3.1.0/src/tss2-esys/esys_crypto_mbed.c:742:40: error: no member named 'Qp' in 'struct mbedtls_ecdh_context'
    if (mbedtls_mpi_lset(&ecdh_context.Qp.Z, 1) != 0)
                          ~~~~~~~~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

Hope it will get resolved quickly :)

### PR DESCRIPTION
**Pull request by biglben**
Updated to mbedTLS 3.0 with backwards compatibility to older versions

Note: MBEDTLS_PRIVATE is used quite a lot. It's not recommended but currently there is no other way. There are open issues at mbedTLS which will add accessor functions.

Fixes #2266 

Signed-off-by: Benjamin Bigler <benjamin.bigler@securiton.ch>

### CODE REVIEW

File: src/tss2-esys/esys_crypto_mbed.c [hunk 1]
```diff
@@ -528,19 +534,38 @@ iesys_cryptmbed_pk_encrypt(TPM2B_PUBLIC * pub_tpm_key,
...
+    mbedtls_rsa_init(&rsa_context);
+#endif
 
     switch(pub_tpm_key->publicArea.nameAlg) {
         case TPM2_ALG_SHA1:
+#if MBEDTLS_VERSION_MAJOR > 2
+            mbedtls_rsa_set_padding(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA1);
+#else
             mbedtls_rsa_init(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA1);
+#endif
```
Comment (williamcroberts) [inline src/tss2-esys/esys_crypto_mbed.c:547]: it would be much simpler if we just have the case statements select the right constants, and then after the switch call rsa_init or rsa_init and set_padding.

Comment (williamcroberts) [reply src/tss2-esys/esys_crypto_mbed.c:547]: Soomething like this:
```diff
diff --git a/src/tss2-esys/esys_crypto_mbed.c b/src/tss2-esys/esys_crypto_mbed.c
index e85dbbddc116..5b544c0ac807 100644
--- a/src/tss2-esys/esys_crypto_mbed.c
+++ b/src/tss2-esys/esys_crypto_mbed.c
@@ -523,6 +523,7 @@ iesys_cryptmbed_random2b(TPM2B_NONCE * nonce, size_t num_bytes)
  * @retval TSS2_ESYS_RC_BAD_VALUE The algorithm of key is not implemented.
  * @retval TSS2_ESYS_RC_GENERAL_FAILURE The internal crypto engine failed.
  */
+//#define MBEDTLS_VERSION_MAJOR 3
 TSS2_RC
 iesys_cryptmbed_pk_encrypt(TPM2B_PUBLIC * pub_tpm_key,
                            size_t in_size,
@@ -533,45 +534,34 @@ iesys_cryptmbed_pk_encrypt(TPM2B_PUBLIC * pub_tpm_key,
 {
     TSS2_RC r = TSS2_RC_SUCCESS;
 
-    mbedtls_rsa_context rsa_context;
-#if MBEDTLS_VERSION_MAJOR > 2
-    mbedtls_rsa_init(&rsa_context);
-#endif
+    int hash = 0;
 
     switch(pub_tpm_key->publicArea.nameAlg) {
         case TPM2_ALG_SHA1:
-#if MBEDTLS_VERSION_MAJOR > 2
-            mbedtls_rsa_set_padding(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA1);
-#else
-            mbedtls_rsa_init(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA1);
-#endif
+            hash = MBEDTLS_MD_SHA1;
             break;
         case TPM2_ALG_SHA256:
-#if MBEDTLS_VERSION_MAJOR > 2
-            mbedtls_rsa_set_padding(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA256);
-#else
-            mbedtls_rsa_init(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA256);
-#endif
+            hash = MBEDTLS_MD_SHA256;
             break;
         case TPM2_ALG_SHA384:
-#if MBEDTLS_VERSION_MAJOR > 2
-            mbedtls_rsa_set_padding(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA384);
-#else
-            mbedtls_rsa_init(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA384);
-#endif
+            hash = MBEDTLS_MD_SHA384;
             break;
         case TPM2_ALG_SHA512:
-#if MBEDTLS_VERSION_MAJOR > 2
-            mbedtls_rsa_set_padding(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA512);
-#else
-            mbedtls_rsa_init(&rsa_context, MBEDTLS_RSA_PKCS_V21, MBEDTLS_MD_SHA512);
-#endif
+            hash = MBEDTLS_MD_SHA512;
             break;
         default:
             return_error(TSS2_ESYS_RC_NOT_IMPLEMENTED,
                          "Hash algorithm not supported");
     }
 
+    mbedtls_rsa_context rsa_context;
+#if MBEDTLS_VERSION_MAJOR > 2
+    mbedtls_rsa_init(&rsa_context);
+    mbedtls_rsa_set_padding(&rsa_context, MBEDTLS_RSA_PKCS_V21, hash);
+#else
+    mbedtls_rsa_init(&rsa_context, MBEDTLS_RSA_PKCS_V21, hash);
+#endif
+
     if (pub_tpm_key->publicArea.unique.rsa.size == 0) {
         goto_error(r, TSS2_ESYS_RC_BAD_VALUE,
                    "Public key size may not be 0", cleanup);
```

Comment (williamcroberts) [reply src/tss2-esys/esys_crypto_mbed.c:547]: not tested....

**Review by williamcroberts — CHANGES_REQUESTED** [review]

File: src/tss2-esys/esys_crypto_mbed.c (hunk 1 above)
Comment (biglben) [reply src/tss2-esys/esys_crypto_mbed.c]: Yes, that's a lot simpler. Init/set padding functions are void, so there's no need for error checking

File: src/tss2-esys/esys_crypto_mbed.c [hunk 2]
```diff
@@ -526,27 +532,37 @@ iesys_cryptmbed_pk_encrypt(TPM2B_PUBLIC * pub_tpm_key,
                            size_t * out_size, const char *label)
 {
     TSS2_RC r = TSS2_RC_SUCCESS;
+    int hash_id = 0;
 
     mbedtls_rsa_context rsa_context;
+#if MBEDTLS_VERSION_MAJOR > 2
+    mbedtls_rsa_init(&rsa_context);
+#endif
```
Comment (williamcroberts) [inline src/tss2-esys/esys_crypto_mbed.c:540]: move this to line 561 then we don't need separate blocks for > version 2

Comment (biglben) [reply src/tss2-esys/esys_crypto_mbed.c]: yes that makes sense

**Review by williamcroberts — APPROVED** [review]
